export * from './admin.module'
export * from './create-gerente'
export * from './list-gerente'
export * from './update-gerente'
export * from './home/home.component'
export * from './admin-routing.module'
export * from './services/admin.service'