export * from './gerente.module';
export * from './home'
export * from  './gerente-routing.module'
export * from './buscar-cliente'
export * from './listar-cliente/listar-cliente.component'
export * from './top5-clientes'
export * from './services/gerente.service'
export * from './modal-rejeitar/modal-rejeitar.component'
export * from './visualizar-cliente'